version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - "15432:5432"
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "andrepraeiro@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "docker"
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
